### ISSUE TITLE
update/replace speed test icon with compass icon

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#101]
- [ ] Change the speed gauge to a compass rose; 
- [ ] replace the play button with “record” or a speed gauge

**Comment by JohnTigue** [comment]
I mulled this over for a bit. 

FIrst, there was confusion: standard record is a **red** button not a square (my bad). OK, consider a red button: that doesn't go well with the current styling color. Maybe an off red, one which isn't maximally saturated. Or we could change the color of all buttons from the current aqua blue to an off-black, which would be similar to the coloring on Google Maps which folks are used to. If that is a trivial CSS tweak I will experiment with it, but minimal changes is desirable at this time.

But red might be very good actually because it would align with the rapidly getting adopted [Material Design](https://www.google.com/design/spec/material-design/introduction.html#) in that Material Design calls for having, if possibly, a single button which acts as the primary call to action, which in our case is "please run a speed test."

Second, perhaps folks just didn't interpret the current speed gauge well. That is, another speed gauge icon might work. I will try both compass and speedometer.

**Comment by critzo** [comment]
Feedback from the call with the city was that we should use a similar color
scheme for the new icon.

**Comment by JohnTigue** [comment]
Yep, I think part of that might have been that us folks in Seattle were imagining the square as record, when actually circle is the record. Something along the lines of the following is the standard users are trained to already:
![](http://thumbs.dreamstime.com/z/media-player-control-button-ui-icon-set-vector-white-app-buttons-home-46012899.jpg)

Nonetheless I can try an aqua-blue circle, which fits the minimal-changes goal. But if we stay in aqua-blue, then compass rose will probably work best. I will give the [Ionicons](http://ionicons.com/) (SVG and MIT licensed) a shot. The source of [Ionicons](https://github.com/driftyco/ionicons/tree/master/src) is on GitHub.

Ionicons has a compass which seems to be rather stylistically consistent with your current look. As with all Ionicons there are two, if not three, flavors: Android, plus iOS and/or "neutral". Below the neutral one is listed first and I think, with regards to the current look, that's the more stylistically consistent of the two:
- [compass neutral](http://fa2png.io/r/ionicons/compass/)
- [compass android](http://fa2png.io/r/ionicons/android-compass/)

**Comment by georgiamoon** [comment]
How about this icon for the compass: http://fortawesome.github.io/Font-Awesome/icon/compass/

Here's a play button: http://fortawesome.github.io/Font-Awesome/icon/play/

I'm a fan of Font Awesome and Flat UI: http://designmodo.github.io/Flat-UI/. Ionicons also look fine.

**Comment by JohnTigue** [comment]
OK, I'll try the ones you recommend.

**Comment by ghost** [comment]
http://www.clipartbest.com/cliparts/4Tb/oEp/4TboEprac.png
http://simpleicon.com/wp-content/uploads/compass-6.png

I was thinking something like that? The Font Awesome one LOOKS great but I am worried it's not intuitive enough.

**Comment by critzo** [comment]
I personally like the second link you posted, Candace.

**Comment by JohnTigue** [comment]
I'm still confused as to what I am supposed to be doing for this Issue.

The title of this Issue is "update/replace speed test icon with compass icon" and the first comment on this page is the two item list:
- [ ] Change the speed gauge to a compass rose;
- [ ] replace the play button with “record” or a speed gauge

Regarding the first of the two items on that list: sounds like from the latest meeting that Bruce finds the speed gauge acceptable. So does that mean there is no need for to "Change the speed gauge to a compass rose."?

Regarding the second item, a red circle record icon just doesn't go well with the Seattle Blue theme, so then the second list item boils down to "replace the play button with a speed gauge." In the "TEST YOUR SPEED!" dialog there already is a speed gauge so two would be confusing. So, any more speed gauges?

That leaves me at "well, we are also talking about a compass icon so that should be used somewhere I guess." I could see having a compass icon on [the thankyou page](http://broadbandmap.seattle.gov/thankyou.html) to go with the text "Explore the map and see how your results compare to other users" i.e. a compass icon for "go back to the map". 

In that case there would be two out of three items in the list on the thankyou page that would have icons. The first would have the compass, and the third would have all the social sharing icons. The middle item would not have an icon. That middle item is "Learn more about this test and how the data will be used" so maybe we could give it the question mark icon.

Please clarify and feel free to shoot down any of these ideas. I as simply trying to enumerate possible interpretations.

**Comment by ghost** [comment]
Compass icon should take you to the map
Speed gauge should take you to the speed test
Question mark should take you to the about/faq
Up to you guys whether we need a "play/record" button at all
No opinion from my end as to what that needs to look like, "record" was a
suggestion from a user but I agree, we would not want it to be in red

On Wed, Jan 20, 2016 at 3:57 AM, John Tigue notifications@github.com
wrote:

> I'm still confused as to what I am supposed to be doing for this Issue.
> 
> The title of this Issue is "update/replace speed test icon with compass
> icon" and the first comment on this page is the two item list:
> - Change the speed gauge to a compass rose;
> - replace the play button with “record” or a speed gauge
> 
> Regarding the first of the two items on that list: sounds like from the
> latest meeting that Bruce finds the speed gauge acceptable. So does that
> mean there is no need for to "Change the speed gauge to a compass rose."?
> 
> Regarding the second item, a red circle record icon just doesn't go well
> with the Seattle Blue theme, so then the second list item boils down to
> "replace the play button with a speed gauge." In the "TEST YOUR SPEED!"
> dialog there already is a speed gauge so two would be confusing. So, any
> more speed gauges?
> 
> That leaves me at "well, we are also talking about a compass icon so that
> should be used somewhere I guess." I could see having a compass icon on the
> thankyou page http://broadbandmap.seattle.gov/thankyou.html to go with
> the text "Explore the map and see how your results compare to other users"
> i.e. a compass icon for "go back to the map".
> 
> In that case there would be two out of three items in the list on the
> thankyou page that would have icons. The first would have the compass, and
> the third would have all the social sharing icons. The middle item would
> not have an icon. That middle item is "Learn more about this test and how
> the data will be used" so maybe we could give it the question mark icon.
> 
> Please clarify and feel free to shoot down any of these ideas. I as simply
> trying to enumerate possible interpretations.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opentechinstitute/bq2geojson/issues/101#issuecomment-173183118
> .

## 

Candace Faber

Seattle, WA

twt: @candacefaber

candacefaber.com http://www.candacefaber.com

**Comment by JohnTigue** [comment]
Agreed. No record button. 

Nice simple mapping of icons to meanings in previous post. I will whip something up for a modified thankyou.html.

**Comment by ghost** [comment]
Awesome.

On Wed, Jan 20, 2016 at 10:41 AM, John Tigue notifications@github.com
wrote:

> Agreed. No record button.
> 
> Nice simple mapping of icons to meanings in previous post. I will whip
> something up for a modified thankyou.html.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opentechinstitute/bq2geojson/issues/101#issuecomment-173319868
> .

## 

Candace Faber

Seattle, WA

twt: @candacefaber

candacefaber.com http://www.candacefaber.com

**Comment by JohnTigue** [comment]
Here's the license for the compass Candace recommended (the second of the two she linked to in this issue, which is the one Chris preferred):  
http://simpleicon.com/license-agreement/

That's about as liberal as it gets so going with it.

Since [the info icon](http://broadbandmap.seattle.gov/images/about.svg) is SVG, I'm using the SVG version of the compass in question, the main page of which is:  
http://simpleicon.com/compass-6.html

**Comment by JohnTigue** [comment]
Ok, I synthesized the notes in this Issue and mutated the goal into a general "clean up the thank you page" task as that seemed to be an area where no one else was working at this time and the page needed some love.

Before:
![thank-you-before](https://cloud.githubusercontent.com/assets/473077/12477180/fa0de7f4-bfe2-11e5-9e97-407a44e591cc.png)

<hr/>

After (my screen capture program failed to record my input pointer but you can see that hover text was added to the social share icons):
![thank-you-after](https://cloud.githubusercontent.com/assets/473077/12477190/05b78d58-bfe3-11e5-98c0-8205ac72d9c3.png)

I am not wedded to any of this and now is a good time for feedback. 

The text is certainly off-script and not final but I wanted to try out a set of shorter phrases than what we had. "Speed tester" in the third item still feels odd to me – just trying out options. Again, I am completely open to feedback and suggested modification.

The compass we originally settled on looked really out of place next to the other two icons (info and share) so I grab [another compass icon](http://publicdomainvectors.org/en/free-clipart/Compass-icon-sign-vector-drawing/17362.html) off the web and put a circle around it for consistency.

The only big enhancement I'm still thinking about is hiding the bottom row of social share buttons until the user clicks on "Share this speed tester." Other than that I'll fine tune alignments/spacings and call it done, after folding in any feedback anyone has.

**Comment by civictechsea** [comment]
John, this looks great. If those share buttons can pop up when you click that link, then that sounds fine to me -- cleaner, better-looking for sure. 

I've asked Michael Mattmiller for some final feedback, but I think we'll want to make some changes to the text so that they are all verbs in the command form and sans punctuation. Something like:

• View all results to-date on a map of Seattle [no period]
• Learn how the City will use this data
• Ask other Seattle residents to take this test

**Comment by JohnTigue** [comment]
Candice's text changes folded in and PR #104 submitted.

The hide/show social-share-buttons will be a separate PR later today.

**Comment by civictechsea** [comment]
Sounds good. John, last thing for now, should the compass icon be the same as the one on the landing page? (Compass rose vs compass face?)

Sent from my City iPhone

On Jan 21, 2016, at 1:18 PM, John Tigue <notifications@github.com<mailto:notifications@github.com>> wrote:

Candice's text changes folded in and PR #104https://github.com/opentechinstitute/bq2geojson/pull/104 submitted.

The hide/show social-share-buttons will be a separate PR later today.

##

**Comment by JohnTigue** [comment]
Oh, absolutely! This sounds like a knock on of where I didn't quite catch the full intent of the updates discussed on Friday's call. I didn't know there was a compass in the mix already. I will make sure they are sync: one and the same – only one compass icon in the code.

**Comment by civictechsea** [comment]
Cool. And no worries. Appreciate all the effort to comply with our many requests!

Sent from my City iPhone

On Jan 21, 2016, at 2:39 PM, John Tigue <notifications@github.com<mailto:notifications@github.com>> wrote:

Oh, absolutely! This sounds like a knock on of where I didn't quite catch the full intent of the updates discussed on Friday's call. I didn't know there was a compass in the mix already. I will make sure they are sync: one and the same - only one compass icon in the code.

##

**Comment by critzo** [comment]
Hi John and Candace,

First, apologies John for delays getting back to you. We'll review your
pull request, and look to merge in some changes to our testing server
tomorrow. We've also experimented with some of this too in a feature
branch, and will cherry pick the best of both.

Best, Chris

**Comment by JohnTigue** [comment]
No rush. Please, take whatever is of value. I ended out getting a bit carried away last night so there was some scope creep which might cause some overlap with these feature branches you mention.

Let me know if there are more Issues I can help with.

**Comment by JohnTigue** [comment]
The most important part is the actual text the users see on those 3 "buttons." That text came from Candace and Michael.
