### ISSUE TITLE
Modifications to the post-test submission form

### ISSUE THREAD

**Issue by critzo** [m-lab/bq2geojson#67]
- [x] Test form should be optional - provide a means for users to not fill out the additional form data. Maybe a button that says "No thanks" for example. If they shared HTML5 geolocation, save the lat/long without saving the other fields. Present the user with a success message after clicking submit or "no thanks"
- [x] Double check the submission of the post-test form. Some test users are reporting that the form will not submit (error message about not filling in form fields is shown), even when all the fields are filled out.

**Comment by critzo** [comment]
@nkinkade it would be helpful if you can take a look at this as well.

**Comment by nkinkade** [comment]
For the 2nd issue (form not submitting): 1) the message is misleading (introduced in @2d3bb89) since it's a server error not an issue with filling out the form or not) 2) the error is something on their server ("Internal Server Error"), likely something to do with uwsgi... I'm written Jim at Seattle asking him to investigate further and provide more information.

**Comment by nkinkade** [comment]
@critzo, which parts of this issue are you assigning to me?  I just want to be sure nothing falls through the cracks, because my understanding as of yesterday as that @gembarrett would handle the first issue (the "No Thanks" button) and that I'd handle the second (form submission not working).  The 2nd issue has been resolved.  Let me know....

**Comment by critzo** [comment]
@nkinkade You are correct. this really should have been two issues. Now that you've covered the second portion, we can reassign to @gembarrett for the first portion.

**Comment by critzo** [comment]
@gembarrett Just pushed to branch "form-opt-out". If you can add the interaction via JS that would be swell.

**Comment by critzo** [comment]
Noting our conversation here that we'll also be introducing a step through form to save screen real estate and to provide an initial user choice on whether to complete the form are all.

**Comment by critzo** [comment]
@gembarrett This is the issue requesting a step-by-step form.
